# Generated by Django 3.1 on 2020-10-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201016_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
